# Configuration file 
# In all scripts numpy is imported as np

BrownianMotion:
  N: 20
  x0: np.random.randn(N, 2)
  mu: np.random.randn(N,2)
  D: np.random.randn(N, 2)
  id: 'BrownianMotion'

Fixed:
  N: 50
  x0: 10 * np.concatenate((np.cos(angles := 2 * np.pi * np.random.rand(N, 1)), np.sin(angles)), axis=1)
  id: 'Fixed'

integrator:
  dt: 0.01

simulator:
  dt: 0.001
  T: 1

environment:
  dimensions: [100, 100]

renderer:
  background_color: 'white'
  agent_colors: ['blue', 'red']
  render_mode: 'pygame'
  render_dt: 0.01

logger:
  log_freq: 0
  save_freq: 10
  comment_enable: False
  log_path: '/../logs'
  log_name: ''

repulsion:
  ity: 3
  dis: 5
