# Configuration file
# In all scripts numpy is imported as np

BrownianMotion:
  N: 20
  x0: 10 * np.random.randn(N, 2)
  mu: '0'
  D: '0.1'
  id: 'Targets'

SimpleIntegrators:
  N: 10
  x0: 10 * np.random.randn(N, 2)
  id: 'Herders'

integrator:
  dt: 0.05

simulator:
  dt: 0.05
  T: 50

environment:
  dimensions: [50, 50]

renderer:
  background_color: 'white'
  agent_colors: ['blue', 'red']
  render_mode: 'pygame'
  render_dt: 0.05

logger:
  activate: False         # True to save logger, False otherwise
  log_freq: 0             # Print every log_freq steps information (0: never print)
  save_freq: 0            # Save every save_freq steps information (0: never save)
  comment_enable: False   # Add initial and final comments to the logger about the experiment
  log_path: '/../logs'    # Path where logger should be saved
  log_name: ''            # String appended to date in the name of the file

repulsion:
  ity: 3
  dis: 2.5
