# Configuration file
# In all scripts numpy is imported as np

BrownianMotion:
  N: 20
  x0: 10 * np.random.randn(N, 2)
  mu: '0'
  D: '0.1'
  id: 'Targets'

SimpleIntegrators:
  N: 10
  x0: 10 * np.random.randn(N, 2)
  id: 'Herders'

integrator:
  dt: 0.05

simulator:
  dt: 0.05
  T: 50

environment:
  dimensions: [50, 50]

renderer:
  background_color: 'white'
  agent_colors: ['blue', 'red']
  render_mode: 'pygame'
  render_dt: 0.05

logger:
  log_freq: 0
  save_freq: 10
  comment_enable: False
  log_path: '/../logs'
  log_name: ''

repulsion:
  ity: 3
  dis: 2.5
