# Configuration file 
# In all scripts numpy is imported as np

BrownianMotion:
  N: 20
  x0: np.random.randn(N, 2)
  mu: np.random.randn(N,2)
  D: np.random.randn(N, 2)
  id: 'BrownianMotion'

Fixed:
  N: 50
  x0: 10 * np.concatenate((np.cos(angles := 2 * np.pi * np.random.rand(N, 1)), np.sin(angles)), axis=1)
  id: 'Fixed'

integrator:
  dt: 0.01

simulator:
  dt: 0.001
  T: 1

environment:
  dimensions: [100, 100]

renderer:
  background_color: 'white'
  agent_colors: ['blue', 'red']
  render_mode: 'matplotlib'
  render_dt: 0.01

logger:
  activate: False         # True to save logger, False otherwise
  log_freq: 0             # Print every log_freq steps information (0: never print)
  save_freq: 0            # Save every save_freq steps information (0: never save)
  comment_enable: False   # Add initial and final comments to the logger about the experiment
  log_path: '/../logs'    # Path where logger should be saved
  log_name: ''            # String appended to date in the name of the file

repulsion:
  ity: 3
  dis: 5
