BrownianMotion:
  N: 2000
  id: BrownianMotion
  initial_conditions:
    mode: Random
    random:
      box:
        lower_bounds:
        - -25
        - -25
        upper_bounds:
        - 25
        - 25
      shape: box
  parameters:
    generate:
      D:
        args:
          loc: 1
          scale: 0.1
        homogeneous: 0
        sampler: normal
      mu:
        positional_args:
        - -1
        - 1
        sampler: uniform
        shape:
        - 2
    mode: generate
  state_dim: 2
FixedPopulation:
  N: 100
  id: Fixed
  initial_conditions:
    mode: Random
    random:
      circle:
        max_radius: 10
        min_radius: 0
      shape: circle
  state_dim: 2
HarmonicRepulsion:
  id: Interaction Force
  parameters:
    generate:
      distance: 10
      strength: 0.1
    mode: generate

PositionLogger:
  activate: 1
  comment_enable: 0
  log_name: Base_Simulation
  log_path: ./logs
  print_freq_step: 10
  save_freq_step: 1
  print_freq_experiment: 1
  save_freq_experiment: 1

environment:
  dimensions:
  - 50
  - 50
integrator:
  dt: 0.01
renderer:
  agent_colors:
  - blue
  - red
  agent_shapes:
  - circle
  - diamond
  agent_sizes:
  - 1
  - 1
  background_color: white
  render_dt: 0.01
  render_mode: pygame
simulator:
  T: 1
  dt: 0.001
