# Configuration file 
# In all scripts numpy is imported as np

BrownianMotion:
  N: 20
  state_dim: 2
  limits : [[-25, 25],[-25,25]]
  x0_mode: From_File 
  x0_path: .\Configuration\Config_data\Initial_Conditions_BrownianMotion.csv 
  mu: np.random.randn(N,2)
  D: np.random.randn(N, 2)
  id: 'BrownianMotion'

FixedPopulation:
  N: 20
  state_dim: 2
  limits : [[-25, 25],[-25,25]]
  x0_mode: Random 
  x0_path: .\Configuration\Config_data\Initial_Conditions_Fixed.csv 
  id: 'Fixed'

integrator:
  dt: 0.01

simulator:
  dt: 0.001
  T: 1

environment:
  dimensions: [50, 50]

renderer:
  background_color: 'white'
  agent_colors: ['blue', 'red']
  agent_shapes: ['circle', 'diamond']
  agent_size: [1, 1]
  render_mode: 'pygame'
  render_dt: 0.01

logger:
  activate: False          # True to save logger, False otherwise
  log_freq: 0             # Print every log_freq steps information (0: never print)
  save_freq: 0            # Save every save_freq steps information (0: never save)
  comment_enable: False   # Add initial and final comments to the logger about the experiment
  log_path: '../../logs'  # Path where logger should be saved
  log_name: ''            # String appended to date in the name of the file


repulsion:
  strength: 3
  max_distance: 2.5

Spatial_Inputs:
  disc_pts: 50
