# Configuration file 
# In all scripts numpy is imported as np

LightSensitive_PTW:
  id: 'Euglena_Gracilis'
  N: 4000
  state_dim: 5
  input_dim: 1

  initial_conditions:
    mode: random
    random:
      shape: box
      box:
        lower_bounds: [-1800, -1000, 20, -3.14, 0]
        upper_bounds: [1800, 1000, 40, 3.14, 0]

  parameters:
    mode: file
    file:
      file_path: ../Configuration/Config_data/Parameters_Euglena.csv

  dt: 0.01

LightPattern:
  pattern_path: ../Configuration/Config_data/BCL.jpeg
  dt: 0.01

integrator:
  dt: 0.01

simulator:
  dt: 0.01
  T: 10  # 300

environment:
  dimensions: [3840, 2160] 
#[1920, 1080] #[3840, 2160]

renderer:
  background_color: 'white'
  agent_colors: ['blue', 'red']
  agent_shapes: ['circle', 'diamond']
  agent_sizes: [20, 20]
  render_mode: 'pygame'
  render_dt: 0.01

logger:
  activate: True          # True to save logger, False otherwise
  log_freq: 0             # Print every log_freq steps information (0: never print)
  save_freq: 1            # Save every save_freq steps information (0: never save)
  save_data_freq: 1
  save_global_data_freq: 1
  comment_enable: False   # Add initial and final comments to the logger about the experiment
  log_path: ./logs    # Path where logger should be saved
  log_name: ''            # String appended to date in the name of the file
