# Configuration file 
# In all scripts numpy is imported as np

LightSensitive_PTW:
  N: 200
  state_dim: 5
  x0_limits : [[-900, 900],[-550,550],[20,40],[-3.14, 3.14],[0,0]]
  x0_mode: Random 
  params_mode: From_File
  params_path: .\Configuration\Config_data\Parameters_Euglena.csv 
  id: 'Euglena_Gracilis'
  dt: 0.01


LightPattern:
  pattern_path: .\Configuration\Config_data\BCL.jpeg 
  dt: 0.5

integrator:
  dt: 0.01

simulator:
  dt: 0.01
  T: 100

environment:
  dimensions: [1920, 1080]

renderer:
  background_color: 'white'
  agent_colors: ['blue', 'red']
  agent_shapes: ['circle', 'diamond']
  agent_size: [20, 20]
  render_mode: 'pygame'
  render_dt: 0.01

logger:
  activate: False          # True to save logger, False otherwise
  log_freq: 0             # Print every log_freq steps information (0: never print)
  save_freq: 100            # Save every save_freq steps information (0: never save)
  comment_enable: False   # Add initial and final comments to the logger about the experiment
  log_path: '../../logs'  # Path where logger should be saved
  log_name: ''            # String appended to date in the name of the file

