AngularFeedback:
  dt: 0.01
LightPattern:
  dt: 0.01
  pattern_path: ./Configuration/Config_data/BCL.jpeg
LightSensitive_PTW:
  N: 4
  dt: 0.01
  id: Euglena_Gracilis
  initial_conditions:
    mode: random
    random:
      box:
        lower_bounds:
        - -1800
        - -1000
        - 20
        - -3.14
        - 0
        upper_bounds:
        - 1800
        - 1000
        - 40
        - 3.14
        - 0
      shape: box
  input_dim: 1
  lim_i:
  - -1920
  - -1080
  - 0
  - -inf
  - -inf
  lim_s:
  - 1920
  - 1080
  - inf
  - inf
  - inf
  parameters:
    file:
      file_path: ./Configuration/Config_data/Parameters_Euglena.csv
    mode: file
  state_dim: 5
PositionLogger:
  activate: 1
  comment_enable: 0
  log_freq: 0
  log_name: Rectangular_Feedback
  log_path: ./logs
  save_data_freq: 0
  save_freq: 500
  save_global_data_freq: 1
Temporal_pulses:
  Period: 10
  dt: 0.01
environment:
  dimensions:
  - 3840
  - 2160
integrator:
  dt: 0.01
renderer:
  agent_colors:
  - blue
  - red
  agent_shapes:
  - circle
  - diamond
  agent_sizes:
  - 20
  - 20
  background_color: white
  render_dt: 0.01
  render_mode: pygame
simulator:
  T: 10
  dt: 0.01
