# Configuration file
# In all scripts numpy is imported as np

BrownianMotion:
  id: 'Targets'
  N: 60
  state_dim: 2

  initial_conditions:
    mode: random
    random:
      shape: circle
      circle:
        max_radius: 30
#      shape: box         # Options: box, circle (only used when mode: Random)
#      box:
#        lower_bounds: [ -30, 10 ]
#        upper_bounds: [ -10, 30 ]

  parameters:
    mode: generate    # Options: import, generate
    generate:
      mu: 0
      D: 1



SimpleIntegrators:
  id: 'Herders'
  N: 10
  state_dim: 2
  v_max: 12

  initial_conditions:
    mode: random
    random:
      shape: circle
      circle:
        max_radius: 30
#      shape: box         # Options: box, circle (only used when mode: Random)
#      box:
#        lower_bounds: [ -50, 40 ]
#        upper_bounds: [ -40, 50 ]

HarmonicRepulsion:
  id: Herders repulsion
  parameters:
    mode: generate
    generate:
      strength: 3
      distance: 2.5

#PowerLawInteraction:
#  p_attr: 2
#  p_rep: 4
#  is_attractive: True
#  L: 100
#  parameters:
#    mode: generate
#    generate:
#      strength_attr: 0
#      strength_rep: 0

integrator:
  dt: 0.05

simulator:
  dt: 0.05
  T: 1000

environment:
  dimensions: [80, 80]
  goal_pos: [0, 0]
  goal_radius: 10

renderer:
  background_color: 'white'
  agent_colors: ['magenta', 'blue']
  agent_shapes: ['circle', 'diamond']
  agent_sizes: [2, 2]
  render_mode: 'pygame'
  render_dt: 0.005
  sensing_radius: 5

logger:
  activate: True         # True to save logger, False otherwise
  log_freq: 0             # Print every log_freq steps information (0: never print)
  save_freq: 1            # Save every save_freq steps information (0: never save)
  save_data_freq: 0
  comment_enable: False   # Add initial and final comments to the logger about the experiment
  log_path: ./logs    # Path where logger should be saved
  log_name: ''            # String appended to date in the name of the file

