# Configuration file
# In all scripts numpy is imported as np

BrownianMotion:
  N: 5
  state_dim: 2

  x0_mode: Random

  x0_shape: circle
  max_initial_radius: 25

  params_mode: Random
  params_names: ["mu","D"]
  params_limits: {mu: [[0.1,0.2],[0.1,0.2]], D: [[0,1],[0,1]]}
  id: 'Targets'

SimpleIntegrators:


  N: 2


  x0_shape: circle
  max_initial_radius: 25

  params_mode: Random
  params_names: ["D"]
  params_limits: {D: [[0,0], [0,0]]}
  state_dim: 2
  x0_mode: Random
  id: 'Herders'

integrator:
  dt: 0.05

simulator:
  dt: 0.05
  T: 10

environment:
  dimensions: [50, 50]
  goal_pos: [0, 0]
  goal_radius: 5

renderer:
  background_color: 'white'
  agent_colors: ['blue', 'red']
  agent_shapes: ['circle', 'diamond']
  agent_size: [1, 1]
  render_mode: 'matplotlib'
  render_dt: 0.05

logger:
  activate: True         # True to save logger, False otherwise
  log_freq: 0             # Print every log_freq steps information (0: never print)
  save_freq: 1            # Save every save_freq steps information (0: never save)
  comment_enable: False   # Add initial and final comments to the logger about the experiment
  log_path: .\logs    # Path where logger should be saved
  log_name: ''            # String appended to date in the name of the file

repulsion:
  strength: 3
  max_distance: 2.5
