BrownianMotion:
  N: 100
  id: Targets
  initial_conditions:
    mode: random
    random:
      circle:
        max_radius: 25
      shape: circle
  parameters:
    generate:
      D: 1
      mu: 0
    mode: generate
  state_dim: 2
HarmonicRepulsion:
  id: Herders repulsion
  parameters:
    generate:
      distance: 2.5
      strength: 3
    mode: generate
SimpleIntegrators:
  N: 10
  id: Herders
  initial_conditions:
    mode: random
    random:
      circle:
        max_radius: 25
      shape: circle
  state_dim: 2
environment:
  dimensions:
  - 50
  - 50
  goal_pos:
  - 0
  - 0
  goal_radius: 5
integrator:
  dt: 0.05
logger:
  activate: 1
  comment_enable: 0
  log_freq: 0
  log_name: ''
  log_path: ./logs
  save_data_freq: 0
  save_freq: 1
renderer:
  agent_colors:
  - blue
  - red
  agent_shapes:
  - circle
  - diamond
  agent_sizes:
  - 1
  - 1
  background_color: white
  render_dt: 0.05
  render_mode: matplotlib
simulator:
  T: 100
  dt: 0.05
