# Configuration file
# In all scripts numpy is imported as np

DampedDoubleIntegrators:
  N: 30
  state_dim: 4
  limits : [[-25, 25],[-25,25]]
  x0_mode: Random 
  D: 1
  damping: 3
  id: 'Targets'

SimpleIntegrators:
  N: 5
  state_dim: 2
  limits : [[-25, 25],[-25,25]]
  x0_mode: Random 
  id: 'Herders'

integrator:
  dt: 0.01

simulator:
  dt: 0.01
  T: 1

environment:
  dimensions: [50, 50]
  goal_pos: [0, 0]
  goal_radius: 5

renderer:
  background_color: 'white'
  agent_colors: ['magenta', 'blue']
  agent_shapes: ['circle', 'diamond']
  agent_size: [1, 1]
  render_mode: 'pygame'
  render_dt: 0.01

logger:
  activate: False         # True to save logger, False otherwise
  log_freq: 1             # Print every log_freq steps information (0: never print)
  save_freq: 1            # Save every save_freq steps information (0: never save)
  comment_enable: False   # Add initial and final comments to the logger about the experiment
  log_path: '../../logs'    # Path where logger should be saved
  log_name: ''            # String appended to date in the name of the file

RepulsionHerderTarget:
  strength: 15
  max_distance: 5
  p: 2

RepulsionTargetTarget:
  strength: 3
  max_distance: 1.5
  p: 2

RepulsionHerderHerder:
  strength: 3
  max_distance: 1.5
  p: 2

Gym:
  num_episodes : 10
  action_bound : 10
  reward_gain : 1
