# Configuration file
# In all scripts numpy is imported as np

DampedDoubleIntegrators:
  N: 50
  state_dim: 4
  x0_limits : [[-25, 25],[-25,25]]
  x0_mode: Random 
  D: 1
  damping: 3
  id: 'Targets'

SimpleIntegrators:
  N: 10
  state_dim: 2
  x0_limits : [[-25, 25],[-25,25]]
  x0_mode: Random 
  params_mode: Random
  params_names: ["D_x","D_y"]
  params_limits: {D_x: [0,0], D_y: [0,0]}
  id: 'Herders'

integrator:
  dt: 0.01

simulator:
  dt: 0.01
  T: 1

environment:
  dimensions: [50, 50]
  goal_pos: [0, 0]
  goal_radius: 5

renderer:
  background_color: 'white'
  agent_colors: ['magenta', 'blue']
  agent_shapes: ['circle', 'diamond']
  agent_size: [1, 1]
  render_mode: 'pygame'
  render_dt: 0.01

logger:
  activate: False         # True to save logger, False otherwise
  log_freq: 1             # Print every log_freq steps information (0: never print)
  save_freq: 1            # Save every save_freq steps information (0: never save)
  comment_enable: False   # Add initial and final comments to the logger about the experiment
  log_path: .\logs        # Path where logger should be saved
  log_name: ''            # String appended to date in the name of the file

RepulsionHerderTarget:
  strength: 15
  max_distance: 5
  p: 2

RepulsionTargetTarget:
  strength: 3
  max_distance: 1.5
  p: 2

RepulsionHerderHerder:
  strength: 3
  max_distance: 1.5
  p: 2

Gym:
  num_episodes : 1
  action_bound : 12
  reward_gain : 1
  num_acts: 5  # For DQN only

  single_agent_env:
    obs_style : "DQN"
    k_1 : 1
    k_2 : 1
    k_3 : 1
    k_4 : 1

  marl_wrapper:
    update_frequency    : 1
    num_closest_targets : 50
    num_closest_herders : 1
    low_level_policy    : "DQN"
    obs_style   : "DQN"
