# Configuration file 
# In all scripts numpy is imported as np

BrownianMotion:
  id: 'BrownianMotion'
  N: 1000
  state_dim: 2

  initial_conditions:
    mode: Random         # Options: Random, From_File
    random:
      shape: box         # Options: box, circle (only used when mode: Random)
      box:
        lower_bounds: [-25, -25]
        upper_bounds: [25, 25]

  parameters:
    mode: generate    # Options: import, generate
    generate:
      mu: 0
      D:
        sampler: normal
        args:
          loc: 0.5
          scale: 0.1
        homogeneous: False

Interaction:
  parameters:
    mode: generate
    generate:
      epsilon: 0.005
      sigma: 1



integrator:
  dt: 0.001

simulator:
  dt: 0.001
  T: 10

environment:
  dimensions: [50, 50]

renderer:
  background_color: 'white'
  agent_colors: ['blue', 'red']
  agent_shapes: ['circle', 'diamond']
  agent_sizes: [1, 1]
  render_mode: 'pygame'
  render_dt: 0.001

logger:
  activate: True          # True to save logger, False otherwise
  log_freq: 0             # Print every log_freq steps information (0: never print)
  save_freq: 1            # Save every save_freq steps information (0: never save)
  save_data_freq: 0
  comment_enable: False   # Add initial and final comments to the logger about the experiment
  log_path: ./logs         # Path where logger should be saved
  log_name: ''            # String appended to date in the name of the file
